// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies species from an image using the Gemini Vision API.
 *
 * - identifySpecies - A function that takes an image and identifies the species.
 * - IdentifySpeciesInput - The input type for the identifySpecies function.
 * - IdentifySpeciesOutput - The return type for the identifySpecies function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifySpeciesInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of an animal, bird, reptile, or insect, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type IdentifySpeciesInput = z.infer<typeof IdentifySpeciesInputSchema>;

const IdentifySpeciesOutputSchema = z.object({
  speciesName: z.string().describe('The common name of the identified species.'),
  scientificName: z.string().describe('The scientific name of the identified species.'),
  confidence: z.number().describe('The confidence percentage of the identification.'),
  speciesClassification: z.string().describe('The species classification (mammal, reptile, etc.).'),
  habitat: z.string().describe('The habitat and regions where the species is found.'),
  diet: z.string().describe('The diet of the species.'),
  conservationStatus: z.string().describe('The conservation status of the species (if applicable).'),
  venomous: z.boolean().optional().describe('Whether the species is venomous (for reptiles).'),
  interestingFacts: z.string().describe('Interesting facts and characteristics of the species.'),
});
export type IdentifySpeciesOutput = z.infer<typeof IdentifySpeciesOutputSchema>;

export async function identifySpecies(input: IdentifySpeciesInput): Promise<IdentifySpeciesOutput> {
  return identifySpeciesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifySpeciesPrompt',
  input: {schema: IdentifySpeciesInputSchema},
  output: {schema: IdentifySpeciesOutputSchema},
  prompt: `You are an expert zoologist specializing in identifying animal species from images. You will analyze the image and provide the following information:

- speciesName: The common name of the identified species.
- scientificName: The scientific name of the identified species.
- confidence: The confidence percentage of the identification.
- speciesClassification: The species classification (mammal, reptile, etc.).
- habitat: The habitat and regions where the species is found.
- diet: The diet of the species.
- conservationStatus: The conservation status of the species (if applicable).
- venomous: Whether the species is venomous (for reptiles) - only include if the animal in the image is a reptile.
- interestingFacts: Interesting facts and characteristics of the species.

Analyze the following image:

{{media url=photoDataUri}}`,
});

const identifySpeciesFlow = ai.defineFlow(
  {
    name: 'identifySpeciesFlow',
    inputSchema: IdentifySpeciesInputSchema,
    outputSchema: IdentifySpeciesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
